[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers --color=yes
markers =
    integration: tests que requieren BD real
filterwarnings =
    ignore::DeprecationWarning
asyncio_mode = auto
